//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DaRT.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DaRT.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use my name for admin calls too.
        /// </summary>
        internal static string Admin_call {
            get {
                return ResourceManager.GetString("Admin_call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show admin chat.
        /// </summary>
        internal static string Admin_chat {
            get {
                return ResourceManager.GetString("Admin_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show admin login messages.
        /// </summary>
        internal static string Admin_login {
            get {
                return ResourceManager.GetString("Admin_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name in chat:.
        /// </summary>
        internal static string Admin_name {
            get {
                return ResourceManager.GetString("Admin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin settings.
        /// </summary>
        internal static string Admin_settings {
            get {
                return ResourceManager.GetString("Admin_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admin request timed out..
        /// </summary>
        internal static string Admin_timeout {
            get {
                return ResourceManager.GetString("Admin_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Admins: {0}.
        /// </summary>
        internal static string Admins_c {
            get {
                return ResourceManager.GetString("Admins_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Allow new messages.
        /// </summary>
        internal static string Allow_mes {
            get {
                return ResourceManager.GetString("Allow_mes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto refresh interval (seconds):.
        /// </summary>
        internal static string Auto_int {
            get {
                return ResourceManager.GetString("Auto_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Refresh.
        /// </summary>
        internal static string Auto_Refresh {
            get {
                return ResourceManager.GetString("Auto_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autoban for messages.
        /// </summary>
        internal static string AutoBan {
            get {
                return ResourceManager.GetString("AutoBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoBan {0} for phrase {1}.
        /// </summary>
        internal static string Autoban_for {
            get {
                return ResourceManager.GetString("Autoban_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Autokick for messages.
        /// </summary>
        internal static string AutoKick {
            get {
                return ResourceManager.GetString("AutoKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AutoKick {0} for phrase {1}.
        /// </summary>
        internal static string Autokick_for {
            get {
                return ResourceManager.GetString("Autokick_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automate.
        /// </summary>
        internal static string Automate {
            get {
                return ResourceManager.GetString("Automate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto refresh interval (seconds):.
        /// </summary>
        internal static string Autoref_int {
            get {
                return ResourceManager.GetString("Autoref_int", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Automatically refresh when players join/leave.
        /// </summary>
        internal static string Autoupdate_join {
            get {
                return ResourceManager.GetString("Autoupdate_join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban.
        /// </summary>
        internal static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban duration.
        /// </summary>
        internal static string Ban_duration {
            get {
                return ResourceManager.GetString("Ban_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Removed Ban!.
        /// </summary>
        internal static string Ban_removed {
            get {
                return ResourceManager.GetString("Ban_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban request ticks:.
        /// </summary>
        internal static string Ban_ticks {
            get {
                return ResourceManager.GetString("Ban_ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban request timed out..
        /// </summary>
        internal static string Ban_timeout {
            get {
                return ResourceManager.GetString("Ban_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban type.
        /// </summary>
        internal static string Ban_type {
            get {
                return ResourceManager.GetString("Ban_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Banned {0} from the server!.
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bans.
        /// </summary>
        internal static string Bans {
            get {
                return ResourceManager.GetString("Bans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bans: {0}.
        /// </summary>
        internal static string Bans_c {
            get {
                return ResourceManager.GetString("Bans_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ban request timed out!.
        /// </summary>
        internal static string Bans_timeout {
            get {
                return ResourceManager.GetString("Bans_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It appears you are using a pretty big ban list.
        ///Please note that your ban list may be cut off because of technical limitations in the RCon protocol.
        ///Using the BRS (Ban Relay Server) is recommended as you won&apos;t encounter such a problem there.
        ///
        ///You can find more informations (including a setup guide) about BRS on the DaRT download page..
        /// </summary>
        internal static string Big_banlist {
            get {
                return ResourceManager.GetString("Big_banlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chat.
        /// </summary>
        internal static string Chat {
            get {
                return ResourceManager.GetString("Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check for Updates on start.
        /// </summary>
        internal static string Check_onStart {
            get {
                return ResourceManager.GetString("Check_onStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Check Updates.
        /// </summary>
        internal static string Check_Updates {
            get {
                return ResourceManager.GetString("Check_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose font.
        /// </summary>
        internal static string Choose_font {
            get {
                return ResourceManager.GetString("Choose_font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear All.
        /// </summary>
        internal static string Clear_all {
            get {
                return ResourceManager.GetString("Clear_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color chat.
        /// </summary>
        internal static string Color_chat {
            get {
                return ResourceManager.GetString("Color_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color filters.
        /// </summary>
        internal static string Color_filters {
            get {
                return ResourceManager.GetString("Color_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show command chat.
        /// </summary>
        internal static string Command_chat {
            get {
                return ResourceManager.GetString("Command_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connecting to {0}:{1}....
        /// </summary>
        internal static string Conn {
            get {
                return ResourceManager.GetString("Conn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show connect / disconnect messages.
        /// </summary>
        internal static string Conn_mess {
            get {
                return ResourceManager.GetString("Conn_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show player connect / disconnect messages.
        /// </summary>
        internal static string Conn_player {
            get {
                return ResourceManager.GetString("Conn_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request players/bans on connect.
        /// </summary>
        internal static string Conn_req {
            get {
                return ResourceManager.GetString("Conn_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect on startup.
        /// </summary>
        internal static string Connect_onStart {
            get {
                return ResourceManager.GetString("Connect_onStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connected!.
        /// </summary>
        internal static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Console.
        /// </summary>
        internal static string Console {
            get {
                return ResourceManager.GetString("Console", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom filters:.
        /// </summary>
        internal static string Custom_filters {
            get {
                return ResourceManager.GetString("Custom_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Thank you for using DaRT!.
        /// </summary>
        internal static string DaRT_thank {
            get {
                return ResourceManager.GetString("DaRT_thank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data base.
        /// </summary>
        internal static string Data_base {
            get {
                return ResourceManager.GetString("Data_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Data settings.
        /// </summary>
        internal static string Data_settings {
            get {
                return ResourceManager.GetString("Data_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show debug messages.
        /// </summary>
        internal static string Debug_mess {
            get {
                return ResourceManager.GetString("Debug_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entry {0} was removed.
        /// </summary>
        internal static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show direct chat.
        /// </summary>
        internal static string Direct_chat {
            get {
                return ResourceManager.GetString("Direct_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  
        ///(Click to download update).
        /// </summary>
        internal static string Down_upd {
            get {
                return ResourceManager.GetString("Down_upd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Duration must be a number!.
        /// </summary>
        internal static string Duration_num {
            get {
                return ResourceManager.GetString("Duration_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get banner.
        /// </summary>
        internal static string Error_banner {
            get {
                return ResourceManager.GetString("Error_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This server is not running BRS or the server configuration is faulty!.
        /// </summary>
        internal static string Error_brs {
            get {
                return ResourceManager.GetString("Error_brs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connection to server was lost. Attempting to reconnect....
        /// </summary>
        internal static string Error_conlost {
            get {
                return ResourceManager.GetString("Error_conlost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to connect. Please make sure that you properly set a password in beserver.cfg and the server is running..
        /// </summary>
        internal static string Error_connect {
            get {
                return ResourceManager.GetString("Error_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Comments can&apos;t be assigned to IPs..
        /// </summary>
        internal static string Error_ip_com {
            get {
                return ResourceManager.GetString("Error_ip_com", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login invalid!.
        /// </summary>
        internal static string Error_login {
            get {
                return ResourceManager.GetString("Error_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show log errors.
        /// </summary>
        internal static string Error_mess {
            get {
                return ResourceManager.GetString("Error_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Could not retrieve news!.
        /// </summary>
        internal static string Error_news {
            get {
                return ResourceManager.GetString("Error_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please connect first!.
        /// </summary>
        internal static string Error_nocon {
            get {
                return ResourceManager.GetString("Error_nocon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred, please try again..
        /// </summary>
        internal static string Error_occ {
            get {
                return ResourceManager.GetString("Error_occ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occured while accessing the log file..
        /// </summary>
        internal static string Error_occ_log {
            get {
                return ResourceManager.GetString("Error_occ_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a valid password!.
        /// </summary>
        internal static string Error_pass {
            get {
                return ResourceManager.GetString("Error_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please enter a valid port!.
        /// </summary>
        internal static string Error_port {
            get {
                return ResourceManager.GetString("Error_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It appears that the server went down. Attempting to reconnect....
        /// </summary>
        internal static string Error_sdown {
            get {
                return ResourceManager.GetString("Error_sdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select a host first..
        /// </summary>
        internal static string Error_sel_host {
            get {
                return ResourceManager.GetString("Error_sel_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Execute....
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expired.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All expired bans were removed from the ban list..
        /// </summary>
        internal static string Expired_removed {
            get {
                return ResourceManager.GetString("Expired_removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This appears to be the first start of the new version of DaRT.
        ///DaRT has found an existing database and will now migrate all of your data to the new format.
        ///A backup of your existing databases will be saved.
        ///
        ///Please continue to start the migration process.
        ///(This may take a while depending on the size of the database).
        /// </summary>
        internal static string First_run {
            get {
                return ResourceManager.GetString("First_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flash window when is called.
        /// </summary>
        internal static string Flash_calls {
            get {
                return ResourceManager.GetString("Flash_calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Official forum thread.
        /// </summary>
        internal static string forum_link {
            get {
                return ResourceManager.GetString("forum_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Geolocating....
        /// </summary>
        internal static string Geoloc {
            get {
                return ResourceManager.GetString("Geoloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Downloading server banner....
        /// </summary>
        internal static string Get_banner {
            get {
                return ResourceManager.GetString("Get_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update bans, get {0} bans..
        /// </summary>
        internal static string Get_n_bans {
            get {
                return ResourceManager.GetString("Get_n_bans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update players, get {0} players..
        /// </summary>
        internal static string Get_n_players {
            get {
                return ResourceManager.GetString("Get_n_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show global chat.
        /// </summary>
        internal static string Global_chat {
            get {
                return ResourceManager.GetString("Global_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Global chats.
        /// </summary>
        internal static string Global_chats {
            get {
                return ResourceManager.GetString("Global_chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show group chat.
        /// </summary>
        internal static string Group_chat {
            get {
                return ResourceManager.GetString("Group_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show GUID verification messages.
        /// </summary>
        internal static string Guid_mess {
            get {
                return ResourceManager.GetString("Guid_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Highlight calls:.
        /// </summary>
        internal static string Hilight {
            get {
                return ResourceManager.GetString("Hilight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Host.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All hosts you ever connected to are listed below.
        /// </summary>
        internal static string Hosts_note {
            get {
                return ResourceManager.GetString("Hosts_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DaRT {0} initialized!.
        /// </summary>
        internal static string InitApp {
            get {
                return ResourceManager.GetString("InitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interval settings.
        /// </summary>
        internal static string Interval_settings {
            get {
                return ResourceManager.GetString("Interval_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kick.
        /// </summary>
        internal static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kicked {0} from the server!.
        /// </summary>
        internal static string Kicked {
            get {
                return ResourceManager.GetString("Kicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last refresh: {0}h ago.
        /// </summary>
        internal static string Last_refresh_h {
            get {
                return ResourceManager.GetString("Last_refresh_h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last refresh: {0}m ago.
        /// </summary>
        internal static string Last_refresh_m {
            get {
                return ResourceManager.GetString("Last_refresh_m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last refresh: {0}s ago.
        /// </summary>
        internal static string Last_refresh_s {
            get {
                return ResourceManager.GetString("Last_refresh_s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This software uses the BattleNET library
        ///created by Marcel de Vries (github.com/marceldev89)
        ///and Robert van der Boorn (github.com/vipeax)
        ///which is licensed under the GNU Lesser General Public License..
        /// </summary>
        internal static string lib_lic {
            get {
                return ResourceManager.GetString("lib_lic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DaRT (DayZ RCon Tool) was developed by Perfler Dominik (github.com/DomiStyle)
        ///in 2012 and translation and improve by Alexander (github.com/NeiroNx) in 2017
        ///as response to the lack of proper RCon applications for DayZ servers
        ///at that given time.
        ///
        ///This overhauled version is provided as a community service and thank you
        ///for all the server administrators out there 
        ///who are still in need for a proper RCon tool - even after such a long time..
        /// </summary>
        internal static string licence {
            get {
                return ResourceManager.GetString("licence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load ban.txt in SQL.
        /// </summary>
        internal static string Load_bans_txt {
            get {
                return ResourceManager.GetString("Load_bans_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load host.
        /// </summary>
        internal static string Load_host {
            get {
                return ResourceManager.GetString("Load_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Loading news....
        /// </summary>
        internal static string Loading_news {
            get {
                return ResourceManager.GetString("Loading_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local chats.
        /// </summary>
        internal static string Local_chats {
            get {
                return ResourceManager.GetString("Local_chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local filters.
        /// </summary>
        internal static string Local_filters {
            get {
                return ResourceManager.GetString("Local_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Local settings.
        /// </summary>
        internal static string Local_settings {
            get {
                return ResourceManager.GetString("Local_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lock server.
        /// </summary>
        internal static string Lock_server {
            get {
                return ResourceManager.GetString("Lock_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log buffer:.
        /// </summary>
        internal static string Log_buffer {
            get {
                return ResourceManager.GetString("Log_buffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Honorable Mention:.
        /// </summary>
        internal static string Mention {
            get {
                return ResourceManager.GetString("Mention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Message.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manually add multiple bans.
        /// </summary>
        internal static string Multiban {
            get {
                return ResourceManager.GetString("Multiban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 
        ///Released {0}
        ///{3}
        ///Download: {1} ({2})
        ///.
        /// </summary>
        internal static string News_download {
            get {
                return ResourceManager.GetString("News_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DaRT version is actual..
        /// </summary>
        internal static string News_noupdate {
            get {
                return ResourceManager.GetString("News_noupdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Released {0} New version: {1} (Size: {2}).
        /// </summary>
        internal static string News_update {
            get {
                return ResourceManager.GetString("News_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notice.
        /// </summary>
        internal static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The player you were about to ban left the game.
        ///Press OK to ban him offline (GUID only) instead..
        /// </summary>
        internal static string Offline_ban_note {
            get {
                return ResourceManager.GetString("Offline_ban_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Permanent.
        /// </summary>
        internal static string perm {
            get {
                return ResourceManager.GetString("perm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ping.
        /// </summary>
        internal static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player Database.
        /// </summary>
        internal static string Player_Database {
            get {
                return ResourceManager.GetString("Player_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player request ticks:.
        /// </summary>
        internal static string Player_ticks {
            get {
                return ResourceManager.GetString("Player_ticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player request timed out..
        /// </summary>
        internal static string Player_timeout {
            get {
                return ResourceManager.GetString("Player_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Players: {0}.
        /// </summary>
        internal static string Players_c {
            get {
                return ResourceManager.GetString("Players_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player request timed out!.
        /// </summary>
        internal static string Players_timeout {
            get {
                return ResourceManager.GetString("Players_timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Port.
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick Ban.
        /// </summary>
        internal static string Quick_Ban {
            get {
                return ResourceManager.GetString("Quick_Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quick ban duration (minutes):.
        /// </summary>
        internal static string Quick_ban_duration {
            get {
                return ResourceManager.GetString("Quick_ban_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Banned for {0} minute(s)..
        /// </summary>
        internal static string Quick_reason {
            get {
                return ResourceManager.GetString("Quick_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reason.
        /// </summary>
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reconnecting....
        /// </summary>
        internal static string Recon {
            get {
                return ResourceManager.GetString("Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reconnected!.
        /// </summary>
        internal static string Reconnected {
            get {
                return ResourceManager.GetString("Reconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing bans....
        /// </summary>
        internal static string Refr_bans {
            get {
                return ResourceManager.GetString("Refr_bans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show refresh messages.
        /// </summary>
        internal static string Refr_mess {
            get {
                return ResourceManager.GetString("Refr_mess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing....
        /// </summary>
        internal static string Refr_now {
            get {
                return ResourceManager.GetString("Refr_now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refreshing players on server....
        /// </summary>
        internal static string Refr_players {
            get {
                return ResourceManager.GetString("Refr_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh (F5).
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload bans.
        /// </summary>
        internal static string Rel_bans {
            get {
                return ResourceManager.GetString("Rel_bans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload events.
        /// </summary>
        internal static string Rel_events {
            get {
                return ResourceManager.GetString("Rel_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload scripts.
        /// </summary>
        internal static string Rel_script {
            get {
                return ResourceManager.GetString("Rel_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remote Base.
        /// </summary>
        internal static string Remote_Base {
            get {
                return ResourceManager.GetString("Remote_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request settings.
        /// </summary>
        internal static string Request_settings {
            get {
                return ResourceManager.GetString("Request_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save hosts.
        /// </summary>
        internal static string Save_hosts {
            get {
                return ResourceManager.GetString("Save_hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save a log file.
        /// </summary>
        internal static string Save_log {
            get {
                return ResourceManager.GetString("Save_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save players.
        /// </summary>
        internal static string Save_players {
            get {
                return ResourceManager.GetString("Save_players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save settings.
        /// </summary>
        internal static string Save_settings {
            get {
                return ResourceManager.GetString("Save_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Saved hosts.
        /// </summary>
        internal static string Saved_hosts {
            get {
                return ResourceManager.GetString("Saved_hosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Say Global.
        /// </summary>
        internal static string Say_Global {
            get {
                return ResourceManager.GetString("Say_Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Say Private.
        /// </summary>
        internal static string Say_Private {
            get {
                return ResourceManager.GetString("Say_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server filters.
        /// </summary>
        internal static string Server_filters {
            get {
                return ResourceManager.GetString("Server_filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server is now locked!.
        /// </summary>
        internal static string Server_locked {
            get {
                return ResourceManager.GetString("Server_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reloaded Bans!.
        /// </summary>
        internal static string Server_relbans {
            get {
                return ResourceManager.GetString("Server_relbans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reloaded Events!.
        /// </summary>
        internal static string Server_relevent {
            get {
                return ResourceManager.GetString("Server_relevent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reloaded Scripts!.
        /// </summary>
        internal static string Server_relscripts {
            get {
                return ResourceManager.GetString("Server_relscripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server is shutting down!.
        /// </summary>
        internal static string Server_shutdown {
            get {
                return ResourceManager.GetString("Server_shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server is now unlocked.
        /// </summary>
        internal static string Server_unlocked {
            get {
                return ResourceManager.GetString("Server_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Scripts log.
        /// </summary>
        internal static string Show_Scripts_log {
            get {
                return ResourceManager.GetString("Show_Scripts_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shutdown.
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to shut the server down?
        ///
        ///Note: This will terminate your current RCon session..
        /// </summary>
        internal static string Shutdown_note {
            get {
                return ResourceManager.GetString("Shutdown_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show side chat.
        /// </summary>
        internal static string Side_chat {
            get {
                return ResourceManager.GetString("Side_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sync Database.
        /// </summary>
        internal static string Sync_Database {
            get {
                return ResourceManager.GetString("Sync_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show timestamps in log.
        /// </summary>
        internal static string Timestamp_log {
            get {
                return ResourceManager.GetString("Timestamp_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If checked, DaRT will automatically refresh your player list at the interval set on the settings page..
        /// </summary>
        internal static string Tip_autorefr {
            get {
                return ResourceManager.GetString("Tip_autorefr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A banner of your server will be shown if your server is registered on GameTracker.\r\nClicking it will bring you to GameTracker..
        /// </summary>
        internal static string Tip_banner {
            get {
                return ResourceManager.GetString("Tip_banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to the server using the details given above..
        /// </summary>
        internal static string Tip_connect {
            get {
                return ResourceManager.GetString("Tip_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect from the server..
        /// </summary>
        internal static string Tip_disconnect {
            get {
                return ResourceManager.GetString("Tip_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load previously used hosts..
        /// </summary>
        internal static string Tip_host {
            get {
                return ResourceManager.GetString("Tip_host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If unchecked, DaRT will queue all incoming messages and add them once new messages are allowed again.
        ///This can prevent unwanted scrolling while you are copying text..
        /// </summary>
        internal static string Tip_message {
            get {
                return ResourceManager.GetString("Tip_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Refresh the current view..
        /// </summary>
        internal static string Tip_refr {
            get {
                return ResourceManager.GetString("Tip_refr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can switch between say and console mode here.
        ///While in say mode you can use global chat to communicate with your players.
        ///Console mode allows you to execute RCon commands directly on the server..
        /// </summary>
        internal static string Tip_say {
            get {
                return ResourceManager.GetString("Tip_say", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adjust your settings..
        /// </summary>
        internal static string Tip_settings {
            get {
                return ResourceManager.GetString("Tip_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contains a useful collection of tools..
        /// </summary>
        internal static string Tip_tools {
            get {
                return ResourceManager.GetString("Tip_tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unban.
        /// </summary>
        internal static string Unban {
            get {
                return ResourceManager.GetString("Unban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show unknown chat.
        /// </summary>
        internal static string Unknown_chat {
            get {
                return ResourceManager.GetString("Unknown_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unlock server.
        /// </summary>
        internal static string Unlock_server {
            get {
                return ResourceManager.GetString("Unlock_server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save Bans in SQL.
        /// </summary>
        internal static string Use_BRS {
            get {
                return ResourceManager.GetString("Use_BRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use Remote data Base.
        /// </summary>
        internal static string Use_Remote {
            get {
                return ResourceManager.GetString("Use_Remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show vehicle chat.
        /// </summary>
        internal static string Vehicle_chat {
            get {
                return ResourceManager.GetString("Vehicle_chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Web Server.
        /// </summary>
        internal static string Web_Server {
            get {
                return ResourceManager.GetString("Web_Server", resourceCulture);
            }
        }
    }
}
